{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oci-management-portal.redisName" . }}
  labels:
    app.kubernetes.io/name: {{ include "oci-management-portal.redisName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "oci-management-portal.redisName" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
