{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oci-management-portal.secretName" . }}
  labels:
    {{- include "oci-management-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  OCI_MGMT_DASH_CLIENT_SECRET: {{ required "secret.clientSecret is required" .Values.secret.clientSecret | quote }}
  {{- with .Values.secret.sessionRedisPassword }}
  OCI_MGMT_DASH_SESSION_REDIS_PASSWORD: {{ . | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secret.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

